### PR TITLE
EXSWHTEC-273 - Implement tests for warp shfl_xor and shfl functions

### PR DESCRIPTION
**Pull request by nives-vukovic**
- Add tests for warp __shfl_xor function
- Add tests for warp __shfl function

### CODE REVIEW

**Review by b-sumner — APPROVED** [review]
LGTM

**Comment by rorake** [comment]
@nives-vukovic 
Will you please resolve the merge conflicts for this PR?

**Comment by nives-vukovic** [comment]
@rorake Conflicts are resolved.

**Comment by mangupta** [comment]
PR has been merged into develop branch via commit 55c04d6169049712eb95549c83a8fdd7cd65147f

**Pull request closed without merging**
