### PR TITLE
EXSWHTEC-75 - Implement tests for hipMemcpyAsync and derivatives

### PR DESCRIPTION
**Pull request by music-dino**
Implement positive and negative unit tests for the following APIs:

hipMemcpyAsync
hipMemcpyDtoHAsync
hipMemcpyHtoDAsync
hipMemcpyDtoDAsync.

### CODE REVIEW

**Comment by mangupta** [comment]
@milos-mozetic / @music-dino : Can someone look into this PR. The previous resolution of the merge conflict https://github.com/ROCm-Developer-Tools/hip-tests/pull/18/commits/1ef552aa3eabebb0d8c23c67e22069b5b4372ae8 looks incorrect. There are some remnants of the merge conflict that can be seen in hipMemcpyAsync.cc.

**Comment by milos-mozetic** [comment]
> @milos-mozetic / @music-dino : Can someone look into this PR. The previous resolution of the merge conflict [1ef552a](https://github.com/ROCm-Developer-Tools/hip-tests/commit/1ef552aa3eabebb0d8c23c67e22069b5b4372ae8) looks incorrect. There are some remnants of the merge conflict that can be seen in hipMemcpyAsync.cc.

@mangupta: Sorry for the inconvenience, now the conflict is resolved appropriately within commit https://github.com/ROCm-Developer-Tools/hip-tests/pull/18/commits/dc236b82908c8c80f7bf7850656c516e1720b380. @music-dino: can you please double-check that the content of hipMemcpyAsync.cc is as expected from your side?

**Comment by chrispaquot** [comment]
> > @milos-mozetic / @music-dino : Can someone look into this PR. The previous resolution of the merge conflict [1ef552a](https://github.com/ROCm-Developer-Tools/hip-tests/commit/1ef552aa3eabebb0d8c23c67e22069b5b4372ae8) looks incorrect. There are some remnants of the merge conflict that can be seen in hipMemcpyAsync.cc.
> 
> @mangupta: Sorry for the inconvenience, now the conflict is resolved appropriately within commit [dc236b8](https://github.com/ROCm-Developer-Tools/hip-tests/commit/dc236b82908c8c80f7bf7850656c516e1720b380). @music-dino: can you please double-check that the content of hipMemcpyAsync.cc is as expected from your side?

Any update?

**Comment by music-dino** [comment]
> > > @milos-mozetic / @music-dino : Can someone look into this PR. The previous resolution of the merge conflict [1ef552a](https://github.com/ROCm-Developer-Tools/hip-tests/commit/1ef552aa3eabebb0d8c23c67e22069b5b4372ae8) looks incorrect. There are some remnants of the merge conflict that can be seen in hipMemcpyAsync.cc.
> > 
> > 
> > @mangupta: Sorry for the inconvenience, now the conflict is resolved appropriately within commit [dc236b8](https://github.com/ROCm-Developer-Tools/hip-tests/commit/dc236b82908c8c80f7bf7850656c516e1720b380). @music-dino: can you please double-check that the content of hipMemcpyAsync.cc is as expected from your side?
> 
> Any update?

The contents seem to be correct. Please proceed with the merge.

**Review by chrispaquot — APPROVED** [review]

**Comment by rorake** [comment]
@music-dino
Will you please resolve the merge conflicts for this PR?

**Comment by music-dino** [comment]
> @music-dino Will you please resolve the merge conflicts for this PR?

Merge conflicts have been resolved, please proceed.

**Pull request merged**
