### PR TITLE
EXSWHTEC-80 - Implement tests for hipModuleGetGlobal 

### PR DESCRIPTION
**Pull request by music-dino**
- Implement positive tests to check basic behavior for globals of different types
- Implement positive and negative parameter tests.

### CODE REVIEW

**Review by chrispaquot — CHANGES_REQUESTED** [review]
Instead of having so many #if HT_NVIDIA, can you remove them and put the tests in the json file to avoid running them?

**Comment by music-dino** [comment]
> Instead of having so many #if HT_NVIDIA, can you remove them and put the tests in the json file to avoid running them?
As far as I am aware, there is no way to skip individual sections via the json, only entire test cases.

**Comment by music-dino** [comment]
> Instead of having so many #if HT_NVIDIA, can you remove them and put the tests in the json file to avoid running them?

As far as I am aware, there is no way to skip individual sections via the json, only entire test cases.

**Comment by chrispaquot** [comment]
> > Instead of having so many #if HT_NVIDIA, can you remove them and put the tests in the json file to avoid running them?
> 
> As far as I am aware, there is no way to skip individual sections via the json, only entire test cases.

@mangupta What should we do here then? Or just skip the whole test for now?

**Comment by chrispaquot** [comment]
> > Instead of having so many #if HT_NVIDIA, can you remove them and put the tests in the json file to avoid running them?
> 
> As far as I am aware, there is no way to skip individual sections via the json, only entire test cases.

OK so instead, create new a new TEST_CASE for the failing ones.

**Comment by music-dino** [comment]
> > > Instead of having so many #if HT_NVIDIA, can you remove them and put the tests in the json file to avoid running them?
> > 
> > 
> > As far as I am aware, there is no way to skip individual sections via the json, only entire test cases.
> 
> OK so instead, create new a new TEST_CASE for the failing ones.

The requested change has been implemented.

**Comment by rakesroy** [comment]
@music-dino ,
Will you please resolve the merge conflicts in this PR?

**Comment by rakesroy** [comment]
PR has been merged into develop branch via commit ce7e67ac39f2b84b997471bbc693b391a085dd41.

**Pull request closed without merging**
