### PR TITLE
EXSWHTEC-113 - Implement tests for hipModuleGetTexRef

### PR DESCRIPTION
**Pull request by music-dino**
- Implement positive tests for hipModuleGetTexRef
- Implement negative tests for hipModuleGetTexRef.

### CODE REVIEW

**Review by chrispaquot — CHANGES_REQUESTED** [review]
Again, pleas remove the #if HT_NVIDIA and add the test to the json file.

**Comment by chrispaquot** [comment]
> Again, pleas remove the #if HT_NVIDIA and add the test to the json file.

Create a new TEST_CASE with the nv cases and add it to json file.

**Comment by music-dino** [comment]
> > Again, pleas remove the #if HT_NVIDIA and add the test to the json file.
> 
> Create a new TEST_CASE with the nv cases and add it to json file.

The requested change has been implemented.

**Comment by rakesroy** [comment]
@music-dino,
Will you please resolve the merge conflicts in this PR?

**Comment by rakesroy** [comment]
PR has been merged into develop branch via commit 72aa591328f6eb38cebca297862b9a96339a6d28.

**Pull request closed without merging**
