### PR TITLE
EXSWHTEC-189 - Implement new and update existing tests for the hipGraph*MemcpyNode1D family of APIs

### PR DESCRIPTION
**Pull request by music-dino**
- Basic positive behavior tests
- Negative parameter tests

### CODE REVIEW

**Review by chrispaquot — APPROVED** [review]

**Comment by mangupta** [comment]
@music-dino : Can you please resolve the merge conflicts for this PR?

**Comment by music-dino** [comment]
> @music-dino : Can you please resolve the merge conflicts for this PR?

Merge conflicts have been resolved, please proceed with review.

**Comment by rorake** [comment]
@music-dino 
Will you please resolve the merge conflicts in this PR?

**Comment by music-dino** [comment]
> @music-dino Will you please resolve the merge conflicts in this PR?

Merge conflicts have been resolved, please proceed.

**Comment by rakesroy** [comment]
PR has been merged into develop branch via commit efddf0908226a3f65ffaeefbf5414f69a58e5ca7.

**Pull request closed without merging**
