### PR TITLE
EXSWHTEC-308 - Migrate and refactor cooperative groups tests from HIP repository

### PR DESCRIPTION
**Pull request by nives-vukovic**
- Migrate grid_group, multi_grid_group, tiled_partition and thread_block_tile tests
- Migrate hipLaunchCooperativeKernel and hipLaunchCooperativeKernelMultiDevice
- Refactor existing thread_block and multi_grid_group tests

### CODE REVIEW

**Review by b-sumner — APPROVED** [review]
Looks fine to me.

**Comment by rorake** [comment]
@nives-vukovic 
1) I don't see files api_failure_tests.cpp & multi_gpu_api_failure_tests.cpp migrated here. 
Are they covered as part of other PRs? In that case please share the PR link.

2) Currently there is a bug on gfx11 when clock64() is used inside a kernel code it hangs. Instead wall_clock64() needs to be used for gfx11. For example: 
https://github.com/ROCm-Developer-Tools/HIP/blob/930469a176d7a005074e201102dc90b038107593/tests/src/runtimeApi/cooperativeGrps/multi_gpu_streams.cpp#L301
You may need to update the testcases for this.

**Comment by nives-vukovic** [comment]
@rorake It is not a simple migration of these negative tests, but more thorough negative testing of these two APIs is done in this PR: https://github.com/ROCm-Developer-Tools/hip-tests/pull/59

As for the clock64 bug, do we need to have two versions of each kernel or wall_clock64 can be used instead for both?

**Comment by rorake** [comment]
@nives-vukovic 
> As for the clock64 bug, do we need to have two versions of each kernel or wall_clock64 can be used instead for both?

Yes, it requires two versions of each kernel. 
One with clock64() for non gfx11 devices and another with wall_clock64() for gfx11 devices.

**Comment by b-sumner** [comment]
> @nives-vukovic
> 
> 1. I don't see files api_failure_tests.cpp & multi_gpu_api_failure_tests.cpp migrated here.
>    Are they covered as part of other PRs? In that case please share the PR link.
> 2. Currently there is a bug on gfx11 when clock64() is used inside a kernel code it hangs. Instead wall_clock64() needs to be used for gfx11. For example:
>    https://github.com/ROCm-Developer-Tools/HIP/blob/930469a176d7a005074e201102dc90b038107593/tests/src/runtimeApi/cooperativeGrps/multi_gpu_streams.cpp#L301
>    You may need to update the testcases for this.

To bel clear, it is incorrect use of clock64() that can cause a hang.  Unfortunately on gfx11, the clock64 counter is only 20 bits wide (IIRC) so it can wrap quickly.

**Comment by nives-vukovic** [comment]
@rorake Modified tests to use kernels with wall_clock64 when device is gfx11.

**Comment by rorake** [comment]
@nives-vukovic,
Thanks for updating the testcases.
Looks fine to me.

**Comment by iassiour** [comment]
Regarding the cooperative groups tests is it correct to use shared memory in this case?
https://github.com/ROCm-Developer-Tools/hip-tests/blob/6d96fbc1f04b03e83091775177f7f40420a8c216/catch/unit/cooperativeGrps/hipCGGridGroupType_old.cc#L44 

I would expect that updates in shared memory from block_0 are not guaranteed to be visible in block_1.

The original test in runtimeApi\cooperativeGrps\hipCGGridGroupTypeViaBaseType.cpp uses global memory.

static __device__ int gm[2];

**Comment by nives-vukovic** [comment]
> Regarding the cooperative groups tests is it correct to use shared memory in this case?
> 
> https://github.com/ROCm-Developer-Tools/hip-tests/blob/6d96fbc1f04b03e83091775177f7f40420a8c216/catch/unit/cooperativeGrps/hipCGGridGroupType_old.cc#L44
> 
> I would expect that updates in shared memory from block_0 are not guaranteed to be visible in block_1.
> 
> The original test in runtimeApi\cooperativeGrps\hipCGGridGroupTypeViaBaseType.cpp uses global memory.
> 
> static **device** int gm[2];

@iassiour Test is modified according to this comment. Global memory should be used instead of shared memory.

**Comment by rorake** [comment]
@nives-vukovic 
Will you please resolve the merge conflicts for this PR?

**Comment by nives-vukovic** [comment]
@rorake Conflicts are resolved. Please let me know if there is any other issue on your build system that should be resolved.

**Comment by mangupta** [comment]
PR has been merged into develop branch via commit e0612f9346c7d16801b92f7d1ac8b1a7401f94d2.

**Pull request closed without merging**
