### PR TITLE
EXSWHTEC-251 - Implement Performance Tests for Stream APIs

### PR DESCRIPTION
**Pull request by milos-mozetic**
- Implement microbenchmarks for the Stream Management APIs.
- Benchmarks are performed for different input parameters, stream types, and different data sizes where applicable.

Depends on: https://github.com/ROCm-Developer-Tools/hip-tests/pull/117

### CODE REVIEW

**Review by gandryey — APPROVED** [review]

**Comment by gandryey** [comment]
Memory pool performance is more complicated than just CPU time for the API calls. It requires to execute kernels and reuse memory.

**Comment by milos-mozetic** [comment]
> Memory pool performance is more complicated than just CPU time for the API calls. It requires to execute kernels and reuse memory.

Sure, we can add this to the performance tests once memory pool APIs are supported by HIP, so that we can observe behavior and implement appropriate tests for that use-case.

**Comment by rorake** [comment]
@milos-mozetic 
Will you please resolve the merge conflicts for this PR?

**Comment by mangupta** [comment]
PR has been merged into develop branch via commit f05f97758eb23e73c65ddbdf1581bcadf298c34a

**Pull request closed without merging**
